-- CREATE USERS TABLE
CREATE TABLE USERS(
    EMAIL VARCHAR2(10) PRIMARY KEY,
    PASS VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(10) NOT NULL
);

-- CREATE BOOKS TABLE
CREATE TABLE BOOKS(
    ISBN VARCHAR2(13) PRIMARY KEY,
    BOOK_NAME VARCHAR2(10) NOT NULL,
    AUTHOR VARCHAR2(10) NOT NULL,
    QTY NUMBER(5) NOT NULL CHECK(QTY >= 0),
    PRICE NUMBER(5) NOT NULL CHECK(PRICE >= 0)
);